version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --all-targets

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo +stable build --release

  test:
    desc: Tests in debug mode
    cmds:
      - cmd: cargo +stable test
