version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage report in text format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates code coverage report in HTML format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --html --open

  cov-badge:
    desc: Generates the detailed code coverage badge
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --json --summary-only | coverio --collapse --tag cov-badge-mdbook-yapp

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  doc-priv:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items --open

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  install:
    desc: Installs preprocessor locally
    cmds:
      - cmd: cargo +stable install mdbook-yapp --path . --force

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo +stable build --release

  test:
    desc: Tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Tests in debug mode using nextest
    cmds:
      - cmd: cargo +stable nextest run

  uninstall:
    desc: Uninstalls preprocessor
    cmds:
      - cmd: cargo uninstall mdbook-yapp
