version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage report
    cmds:
      - cmd: cargo llvm-cov --no-cfg-coverage
      - cmd: cargo llvm-cov report --html
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/target/llvm-cov/html/index.html\n"

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc-priv:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --no-deps --document-private-items --open

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  install:
    desc: Installs preprocessor locally
    cmds:
      - cmd: cargo +stable install mdbook-yapp --path . --force

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo +stable build --release

  test:
    desc: Tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Tests in debug mode using nextest
    cmds:
      - cmd: cargo +stable nextest run

  uninstall:
    desc: Uninstalls preprocessor
    cmds:
      - cmd: cargo uninstall mdbook-yapp
