# Linux Musl x86_64

name: Linux

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - run: cargo build --release --target=x86_64-unknown-linux-gnu
